### ISSUE TITLE
add dataset reference to model

### ISSUE THREAD

**Issue by linalex** [Azure/azureml-sdk-for-r#284]
what is the R equivalent of tuple in R?

**Comment by mx-iao** [comment]
Hi @linalex, can you point us to the specific method you are referring to? You can import the reticulate package and then use the `tuple()` method, but we generally want to avoid requiring that of users. So if there are any methods where you're having issues with this please let us know and we'll address them.

**Comment by linalex** [comment]
dt <- get_dataset_by_name(ws, "name", version = "latest")
model_new$add_dataset_references("dt") # what is a tuple in R, what shall I put here?

**Comment by mx-iao** [comment]
I see. Can you try:
```
library(reticulate)
dt <- get_dataset_by_name(ws, "name", version = "latest")
model_new$add_dataset_references(tuple("your dataset purpose", dt))
```
Another option for associating datasets with a model is during registration time: when you call [`register_model()`](https://azure.github.io/azureml-sdk-for-r/reference/register_model.html) you can specify the `datasets` parameter; it will take a list of tuples & you can specify it similar to above. @diondrapeck we should change the type for the `datasets` parameter so it doesn't require user to use tuples directly.

**Comment by linalex** [comment]
` Error in py_call_impl(callable, dots$args, dots$keywords) : 
  WebserviceException: WebserviceException:
	Message: Invalid dataset of type <class 'str'> passed, must be of type Dataset or DatasetSnapshot
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Invalid dataset of type <class 'str'> passed, must be of type Dataset or DatasetSnapshot"
    }
} `

error with `tuple()` method.  

for `register_model()`, TabluarDataset not suported. Is it expected.

Additionally, is the plan of the R SDK just to provide wrapper of python SDK?

**Comment by mx-iao** [comment]
Sorry, I had a typo, should be a list of tuples:
```
library(reticulate)
dt <- get_dataset_by_name(ws, "name", version = "latest")
model_new$add_dataset_references(list(tuple("your dataset purpose", dt)))
```
However this does yield the following error: `Message: Invalid dataset of type <class 'azureml.data.tabular_dataset.TabularDataset'> passed, must be of type Dataset or DatasetSnapshot`. I believe this is a bug with the datasets service - they recently deprecated a class and I don't think they updated the method. @MayMSFT FYI can you take a look?

I was able to successfully register a model with a TabularDataset with the following code - can you let me know if it's not working for you?
```
register_model(ws, model_path = './path-to-my-model', model_name = 'my-model', datasets = list(tuple("your dataset purpose", dt)))
```
The string you provide to the tuple is a key describing the dataset-model association. If you want to then access the datasets associated with your model you can do so:
`model_new$datasets['your dataset purpose']`

Yes, the R SDK is a convenience wrapper for some of the core functionalities available in the Python SDK.

Let me know if you're still having issues with the above.

**Comment by mx-iao** [comment]
Just checked - the bug with using `add_dataset_references` has been fixed in the Python SDK. If you would like to use that method you can update the underlying Python SDK via `azuremlsdk::install_azureml(version = "1.1.5.1")`. We will be releasing a new version to CRAN soon where we will update the underlying Python SDK.

**Comment by mx-iao** [comment]
Closing this issue now - please reopen if you have further issues/questions.

**Comment by coolkate3738** [comment]
Hi @mx-iao !
 I am still experiencing same issue even after your tuple recommendation above , I am trying to register a dataset in register_model command: please see my code 
`class(holdout_data_test)`

> "data.table" "data.frame"

`model <- register_model(ws, 
                        model_path = model_path, 
                        model_name = "cpm_model",
                        description = "freight cost prediction",
                        datasets = list(tuple("validation", holdout_data_test)))`

> ERROR - Invalid dataset of type <class 'dict'> passed, must be of type Dataset or DatasetSnapshot Error in py_call_impl(callable, dots$args, dots$keywords) : 
  WebserviceException: WebserviceException:
	Message: Invalid dataset of type  passed, must be of type Dataset or DatasetSnapshot
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Invalid dataset of type  passed, must be of type Dataset or DatasetSnapshot"
    }
}

Please advise as I am losing the world to live :(
